### ISSUE TITLE
Is the DLL mising

### ISSUE THREAD

**Issue by ThomasBSmits** [dannypolkinhorn/SaveAsNewCentral#1]
I've been trying to use the tool, but the zipfile does not contain the DLL file(?)
![dll](https://cloud.githubusercontent.com/assets/24244579/20703684/f00ce422-b61c-11e6-8c95-3a7ef22ed9fc.jpg)

**Comment by dannypolkinhorn** [comment]
Hi Thomas,

With Github (and this project as well), only the source code is included.  You will need to compile the code yourself using Visual Studio.  You can use the free Community edition to compile it.  https://www.visualstudio.com/downloads/
